server:
  port: 9091

spring:
  zipkin:
    enabled: false
  application:
    name: spring-slueth-demo-1
  profiles:
    active: demo
  sleuth:
    span-filter:
      enabled: true
    enabled: true
    baggage:
      correlation-fields: 'X-Correlation-Id'
      remote-fields: 'X-Correlation-Id'
      local-fields: 'X-Client-Ip'
    log:
      slf4j:
        enable: true
    web:
      webclient.enabled: true
      client.enabled: true
      skip-pattern: (\S*\/health$|\S*\/info$)
app:
  demo2:
    host: http://localhost:9092/demo2
    endpoints:
      all-covid-statistic: /covid
      latest-covid-statistic: /covid/latest
logging:
  level:
    app: INFO
  pattern.console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} | %-5level | %t | %X{X-Correlation-Id:-} | %X{X-Client-Ip:-} | %c{1} | %msg%n"