debug: true
server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:h2:mem:///./db/testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true